### ISSUE TITLE
shadow-cljs works with deps.edn on Windows

### ISSUE THREAD

**Issue by thheller** [cark/clojure-windows-cli-issues#1]
The readme lists shadow-cljs as not working with `deps.edn` on Windows. That changed one or two releases ago where I adjusted it to properly invoke the powershell commands and it seems to be working fine now.

**Comment by cark** [comment]
Ah I must confess I haven't tried again since I do have workarounds in place now.
I'll fix the readme, though I still think command line parity would be best.
